// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAICiio9147zLqRPGbu0Ykhs2885205ydk',
    appId: '1:900797432580:web:db97defdd1408816bd4651',
    messagingSenderId: '900797432580',
    projectId: 'flutter-interview-12a07',
    authDomain: 'flutter-interview-12a07.firebaseapp.com',
    storageBucket: 'flutter-interview-12a07.firebasestorage.app',
    measurementId: 'G-RHBFDHRXZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3dlb-95iYG4wxd2RtZ-UDsuWTWqPicVk',
    appId: '1:900797432580:android:03668e2a628904dfbd4651',
    messagingSenderId: '900797432580',
    projectId: 'flutter-interview-12a07',
    storageBucket: 'flutter-interview-12a07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1JC7X_dlQavpy-WeI3AUia_tBJeI6wBE',
    appId: '1:900797432580:ios:832423e4b6e9c88ebd4651',
    messagingSenderId: '900797432580',
    projectId: 'flutter-interview-12a07',
    storageBucket: 'flutter-interview-12a07.firebasestorage.app',
    iosBundleId: 'com.example.flutterInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1JC7X_dlQavpy-WeI3AUia_tBJeI6wBE',
    appId: '1:900797432580:ios:832423e4b6e9c88ebd4651',
    messagingSenderId: '900797432580',
    projectId: 'flutter-interview-12a07',
    storageBucket: 'flutter-interview-12a07.firebasestorage.app',
    iosBundleId: 'com.example.flutterInterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAICiio9147zLqRPGbu0Ykhs2885205ydk',
    appId: '1:900797432580:web:fb0430595989d7a2bd4651',
    messagingSenderId: '900797432580',
    projectId: 'flutter-interview-12a07',
    authDomain: 'flutter-interview-12a07.firebaseapp.com',
    storageBucket: 'flutter-interview-12a07.firebasestorage.app',
    measurementId: 'G-GHEMB8CXQ8',
  );
}
